flowchart TD

    A[GitHub Actions CI] --> B[Job backend]
    B --> C[Job frontend]
    C --> D[Job deploy]
    B --> D

    subgraph Backend [Pipeline Backend]
        B1[Gradle test + coverage] --> B2[Gradle build JAR]
        B2 --> B3["Upload artifact: backend-jar"]
        B2 --> B5["SonarCloud Scan Backend"]
    end
    B --> B1

    subgraph Frontend [Pipeline Frontend]
        C1[Angular test + coverage] --> C2[Angular build dist]
        C2 --> C3["Upload artifact: frontend-dist"]
        C2 --> C5["SonarCloud Scan Frontend"]
    end
    C --> C1

    subgraph Deploy [Pipeline Deploy]
        D1["Download artifacts"] --> D3["Prepare build context"]
        D3 --> E["docker build & push (GHCR)"]
    end
    D --> D1

    E --> F[Dockerfile.deploy]

    subgraph Container [Conteneur Final]
        F --> G["FROM eclipse-temurin:17-jre"]
        G --> H["Install Caddy + Supervisor"]
        H --> I["COPY backend.jar"]
        H --> J["COPY frontend-dist"]

        I --> K["Image finale"]
        J --> K

        K --> L[Supervisor]
        L --> M["Java -jar backend.jar"]
        L --> N["Caddy"]

        N --> O["Serve frontend"]
        N --> P["Proxy -> backend:8080"]
    end

    style B3 fill:#90EE90
    style C3 fill:#90EE90
    style D1 fill:#87CEEB
    style E fill:#FFD700
    style F fill:#FFA500
    style B5 fill:#4e9bcd
    style C5 fill:#4e9bcd
